server:
  port: 8081
  servlet:
    context-path: /dream
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://106.15.199.3:3306/plansun
    username: root
    password: Lili520
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 106.15.199.3
    port: 6379
    password: Lili520
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: pro.xiaoyang.dream.base
